@startuml
left to right direction
actor "利用者" as Viewer
actor "管理操作利用者" as Manager

note bottom of Manager
    利用者向け操作に加えて
    管理操作も
    実行可能
end note

package "MediaViewer" {
    Viewer <|- Manager
    package "メディア参照" {
        Viewer --> (メディア一覧表示)
        Viewer --> (メディア検索)
        (メディア検索) -> (メディア一覧表示)
        (メディア一覧表示) --> (メディア詳細表示)
        (メディア詳細表示) ..> (漫画閲覧) : 漫画のとき
        (メディア詳細表示) ..> (動画再生) : 動画のとき
    }
    package "管理者によるメディア管理" {
        Manager --> (メディア登録)
        Manager --> (メディア更新)
        Manager --> (メディア削除)
    }
}
@enduml
