@startuml 

title メディア更新

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: メディア更新ボタン押下
ブラウザ -> サーバー: メディア更新\npatch /api/media/{mediaId}
ブラウザ <-- サーバー: レスポンス
alt メディア更新成功
    ブラウザ -> サーバー: メディア詳細画面取得\nget /detail/{mediaId}
    ブラウザ <-- サーバー: メディア詳細画面HTML
    ユーザー <- ブラウザ: メディア詳細画面を表示
else
    ユーザー <- ブラウザ: 更新失敗を表示
end

@enduml
