@startuml 

title メディアファイル削除

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: メディアファイル削除ボタン押下
ブラウザ -> ブラウザ: メディアファイルを一覧から削除
alt 削除したメディアファイルより大きいページ番号のメディアファイルが存在する
    ブラウザ -> ブラウザ: ページ番号を1減らす
end
ユーザー <- ブラウザ: 変更後の画面を表示

@enduml
