@startuml 

title メディア更新

actor 閲覧者
participant ブラウザ

閲覧者 -> ブラウザ: メディア更新ボタン押下
ブラウザ -> サーバー: メディア更新\npatch /api/media/{mediaId}
ブラウザ <-- サーバー: レスポンス
alt メディア更新成功
    ブラウザ -> サーバー: メディア詳細画面取得\nget /detail/{mediaId}
    ブラウザ <-- サーバー: メディア詳細画面HTML
    閲覧者 <- ブラウザ: メディア詳細画面を表示
else
    閲覧者 <- ブラウザ: 更新失敗を表示
end

@enduml
