@startuml 

title 下ページと入れ替え

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: メディアファイル番号入れ替え上ボタン押下
ブラウザ -> ブラウザ: 1つ小さいページのメディアファイルと位置を入れ替える
ブラウザ -> ブラウザ: ページ番号を1減らす
ブラウザ -> ブラウザ: 入れ替えたメディアファイルのページ番号を1増やす
ユーザー <- ブラウザ: 変更後の画面を表示

@enduml
