@startuml 

title ファイル選択

actor 閲覧者
participant ブラウザ

閲覧者 -> ブラウザ: ファイル選択エリア押下
閲覧者 <- ブラウザ: ファイル選択ダイアログを表示
閲覧者 -> ブラウザ: ファイルを選択
ブラウザ -> ブラウザ: 選択されたファイルをメディアファイルとして一番下に追加
閲覧者 <- ブラウザ: 変更後の画面を表示

@enduml
