@startuml 

title メディア登録

actor 閲覧者
participant ブラウザ

閲覧者 -> ブラウザ: メディア登録ボタン押下

ブラウザ -> サーバー: メディア登録\npost /api/media
ブラウザ <-- サーバー: レスポンス
alt メディア登録成功
    ブラウザ -> サーバー: メディア一覧画面取得\nget /detail/media/{mediaId}
    ブラウザ <-- サーバー: メディア一覧画面HTML
    閲覧者 <- ブラウザ: メディア一覧画面を表示
else
    閲覧者 <- ブラウザ: 登録失敗を表示
end

@enduml
