@startuml

hide circle

entity media {
  *media_id : int <<PK>>
  --
  title : text
  created_at : datetime
  updated_at : datetime
}

entity content {
  *content_id : int <<PK>>
  --
  media_id : int <<FK>>
  content_path : text
  thumbnail_path : text
  page : int
}

entity category {
  *category_id : int <<PK>>
  --
  name : text
}

entity tag {
  *tag_id : int <<PK>>
  --
  category_id : int <<FK>>
  name : text
}

entity media_tag {
  *media_id : int <<PK>> <<FK>>
  *tag_id : int <<PK>> <<FK>>
}

@enduml
