@startuml

title get /summary

participant クライアント
participant サーバー
database データベース

クライアント -> サーバー: リクエスト

サーバー -> データベース: メディアを検索
サーバー <-- データベース: メディア一覧

クライアント <-- サーバー: メディア一覧画面HTML

@enduml
