@startuml

hide circle

note as G1
  ・テーブル名は単数形で統一する
  ・原則NOT NULL（例外は <<nullable>> で明示）
end note

entity session {
  *session_token : text <<PK>>
  --
  user_id : int <<FK>>
  expires_at : datetime
}

entity user {
  *user_id : int <<PK>>
  --
  username : text
  password_hash : text
  salt : text
  created_at : datetime
  updated_at : datetime
}

entity media {
  *media_id : int <<PK>>
  --
  title : text
  created_at : datetime
  updated_at : datetime
}

entity content {
  *content_id : text <<PK>>
  --
  media_id : int <<FK>>
  position : int
  <<unique(media_id, position)>>
}

entity favorite {
  *favorite_id : int <<PK>>
  *user_id : int <<FK>>
  *media_id : int <<FK>>
  --
  added_at : datetime
  <<unique(user_id, media_id)>>
}
note bottom: favorite_idとadded_atで追加順を一意とする

entity queue {
  *queue_id : int <<PK>>
  *user_id : int <<FK>>
  *media_id : int <<FK>>
  --
  added_at : datetime
  <<unique(user_id, media_id)>>
}
note bottom: queue_idとadded_atで追加順を一意とする

entity category {
  *category_id : int <<PK>>
  --
  name : text
  <<unique(name)>>
}

entity tag {
  *tag_id : int <<PK>>
  --
  category_id : int <<FK>>
  name : text
  <<unique(category_id, name)>>
}
note right
  レコードを削除することは基本的にない。
  メディアと紐づくタグが0件になっても
  再度利用される可能性があるため。
end note

entity media_tag {
  media_id : int <<FK>>
  category_id : int <<FK>>
  tag_id : int <<FK>> <<nullable>>
  priority : int
  <<unique(media_id, category_id, tag_id)>>
  <<unique(media_id, category_id, priority)>>
}

session |o--|| user
user ||--o{ favorite
user ||--o{ queue
media ||-u-|{ content
media ||--o{ favorite
media ||--o{ queue
media ||--o{ media_tag
tag ||--o{ media_tag
category ||--o{ media_tag
category ||--o{ tag
@enduml
