@startuml

title put /api/favorite/{mediaId}

クライアント -> サーバー: リクエスト
!include ./auth_guard.puml

participant クライアント
participant サーバー
database データベース

サーバー -> データベース: トランザクション開始
サーバー -> データベース: お気に入りに追加
サーバー <-- データベース: 追加完了
break お気に入り追加失敗
    サーバー -> データベース: ロールバック
    サーバー <-- データベース: ロールバック完了
    クライアント <-- サーバー: 200 失敗
end
サーバー -> データベース: コミット
サーバー <-- データベース: コミット完了

クライアント <-- サーバー: 200 成功

@enduml
