@startuml

title post /login


participant クライアント
participant サーバー
database データベース

クライアント -> サーバー: リクエスト
サーバー -> データベース: ユーザーID、パスワード存在チェック
サーバー <-- データベース: 結果

break ユーザーID、パスワードが存在しない
    クライアント <-- サーバー: 200 ログイン失敗
end

サーバー -> データベース: トランザクション開始
サーバー -> データベース: ユーザーの既存セッション削除
サーバー <-- データベース: セッション削除完了
サーバー -> サーバー: セッションID作成
サーバー -> データベース: セッション保存
サーバー <-- データベース: セッション保存完了
サーバー -> データベース: コミット
サーバー <-- データベース: コミット完了

break セッション作成、セッション保存失敗
    クライアント <-- サーバー: 200 ログイン失敗
end

クライアント <-- サーバー: 200 ログイン成功、セッションID

@enduml
