@startuml

title post /logout

クライアント -> サーバー: リクエスト
!include ./auth_guard.puml

participant クライアント
participant サーバー
database データベース

サーバー -> データベース: トランザクション開始
break メディア、アイテム保存に失敗
    サーバー -> データベース: ロールバック
    サーバー <-- データベース: ロールバック完了
    クライアント <-- サーバー: 200 ログアウト失敗
end
サーバー -> データベース: コミット
サーバー <-- データベース: コミット完了

クライアント <-- サーバー: 200 ログアウト成功

@enduml
