@startuml

title delete /api/queue/{mediaId}

クライアント -> サーバー: リクエスト
!include ./auth_guard.puml

participant クライアント
participant サーバー
database データベース

サーバー -> データベース: トランザクション開始
サーバー -> データベース: あとで見るから削除
サーバー <-- データベース: 削除完了
break あとで見る削除失敗
    サーバー -> データベース: ロールバック
    サーバー <-- データベース: ロールバック完了
    クライアント <-- サーバー: 200 失敗
end
サーバー -> データベース: コミット
サーバー <-- データベース: コミット完了

クライアント <-- サーバー: 200 成功

@enduml
