openapi: 3.1.0
info:
  title: Media App API
  version: 1.0.0
servers:
  - url: https://example.com
paths:
  # ページURL
  /page/login:
    $ref: './paths/page/login.yaml'
  /page/summary:
    $ref: './paths/page/summary.yaml'
  /page/detail/{mediaId}:
    $ref: './paths/page/detail.mediaId.yaml'
  /page/viewer/{mediaId}/{page}:
    $ref: './paths/page/viewer.mediaId.page.yaml'
  /page/search:
    $ref: './paths/page/search.yaml'
  /page/favorite:
    $ref: './paths/page/favorite.yaml'
  /page/queue:
    $ref: './paths/page/queue.yaml'
  /page/error:
    $ref: './paths/page/error.yaml'
  /page/entry:
    $ref: './paths/page/entry.yaml'
  /page/edit/{mediaId}:
    $ref: './paths/page/edit.mediaId.yaml'

  # WebAPI
  /api/login:
    $ref: './paths/api/login.yaml'
  /api/logout:
    $ref: './paths/api/logout.yaml'
  /api/media:
    $ref: './paths/api/media.yaml'
  /api/media/{mediaId}:
    $ref: './paths/api/media.mediaId.yaml'
  /api/favorite/{mediaId}:
    $ref: './paths/api/favorite.mediaId.yaml'
  /api/queue/{mediaId}:
    $ref: './paths/api/queue.mediaId.yaml'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionID
  responses:
    RedirectError:
      description: エラー画面リダイレクト
      headers:
        Location:
          description: リダイレクト先のURL
          schema:
            type: string
            example: /error
    UnauthorizedApi:
      description: セッションIDが無効、または未送信
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                description: 認証失敗メッセージ
                type: string
          examples:
            fail:
              summary: 認証失敗
              value: {
                message: 認証に失敗しました
              }
