@startuml

title ログアウト

actor ユーザー
participant ブラウザ
participant サーバー

ユーザー -> ブラウザ: ログアウト押下
ブラウザ -> サーバー: ログアウト処理\npost /api/logout
ブラウザ <-- サーバー: レスポンス
ブラウザ -> ブラウザ: セッションID破棄
ブラウザ -> サーバー: ログイン画面取得\nget /login
ブラウザ <-- サーバー: ログイン画面HTML
ユーザー <- ブラウザ: ログイン画面を表示

@enduml
