@startuml

title あとで見る解除

actor ユーザー
participant ブラウザ
participant サーバー

ユーザー -> ブラウザ: あとで見るボタン押下
ブラウザ -> サーバー: あとで見る解除\ndelete /api/queue/{mediaId}
ブラウザ <-- サーバー: レスポンス
ブラウザ -> ブラウザ: あとで見るボタンを解除状態に変更
ユーザー <- ブラウザ: 変更後の画面を表示

@enduml
