@startuml

title タイトル押下

actor 閲覧者
participant ブラウザ
participant サーバー

閲覧者 -> ブラウザ: タイトル押下
ブラウザ -> サーバー: メディア一覧画面取得\nget /detail/{mediaId}
ブラウザ <-- サーバー: メディア詳細画面HTML
閲覧者 <- ブラウザ: メディア詳細画面を表示

@enduml
