@startuml

title ページ変更

actor 閲覧者
participant ブラウザ
participant サーバー

閲覧者 -> ブラウザ: サムネイル押下
ブラウザ -> サーバー: メディア一覧画面取得\nget /summary?summaryPage={ページ番号}
note left
    summaryPage以外は付与したまま
end note
ブラウザ <-- サーバー: メディア詳細画面HTML
閲覧者 <- ブラウザ: メディア詳細画面を表示

@enduml
