@startuml

state "利用中" as InUse {
    summary : メディア一覧
    search : メディア検索
    navigation : ナビゲーション

    state "管理者" as Admin {
        entry : メディア登録
    }
}

' 共通
InUse.navigation --> InUse.summary : トップ
InUse.navigation --> InUse.search : メディア検索を選択
InUse.navigation --> InUse.Admin.entry : メディア登録を選択

@enduml
