@startuml

state "ログイン済" as Signin {
    summary : メディア一覧
    search : メディア検索
    navigation : ナビゲーション

    state "管理者" as Admin {
        entry : メディア登録
    }
}

' 共通
Signin.navigation --> Signin.summary : トップ
Signin.navigation --> Signin.search : メディア検索を選択
Signin.navigation --> Signin.Admin.entry : メディア登録を選択

@enduml
