@startuml

state "ログイン済" as Signin {
    summary : メディア一覧
    detail : メディア詳細
    viewer : メディアビューアー
}

' 共通
[*] --> Signin.summary
Signin.summary --> Signin.detail : メディアを選択
Signin.detail --> Signin.viewer : サムネイル選択
Signin.viewer --> Signin.detail : ビューアーを閉じる

@enduml
