@startuml

title ログアウト処理

actor ユーザー
participant クライアント
participant サーバー

ユーザー -> クライアント: ログアウト押下
クライアント -> サーバー: ログアウト処理\npost /logout
クライアント <-- サーバー: ログアウト結果
クライアント -> クライアント: セッションID破棄
クライアント -> サーバー: ログイン画面取得\nget /login
クライアント <-- サーバー: 画面HTML

@enduml
