@startuml
' skinparam linetype ortho

package メディア集約 {

    entity メディア {
        <<aggregate-root>>
    }

    object メディアID {
        <<value-object>>
    }

    object メディアタイトル {
        <<value-object>>
    }

    object コンテンツID {
        <<value-object>>
    }

    object タグ {
        <<value-object>>
    }

    object カテゴリー {
        <<value-object>>
    }

    object ラベル {
        <<value-object>>
    }

    object コンテンツ取得結果 {
        <<domain-result>>
    }

    object 取得成功コンテンツ {
        <<domain-result>>
    }

    object 取得失敗コンテンツ {
        <<domain-result>>
    }

    コンテンツ取得結果 <|-- 取得成功コンテンツ
    コンテンツ取得結果 <|-- 取得失敗コンテンツ

    取得成功コンテンツ "1" o-- "1" コンテンツID : 対象コンテンツ

    ' メディアの振る舞いの結果であることを表現
    メディア ..> コンテンツ取得結果 : コンテンツ位置を指定して判定する

    ' ===== 既存定義 =====
    メディア "1" o-- "1" メディアID
    メディア "1" o-- "1" メディアタイトル
    メディア "1" o-- "1..*" コンテンツID
    メディア "1" o-- "0..*" タグ
    メディア "1" o-l- "0..*" カテゴリー : カテゴリー優先度

    タグ "1" o-- "1" カテゴリー
    タグ "1" o-- "1" ラベル
}

package ユーザー集約 {

    entity ユーザー {
        <<aggregate-root>>
    }

    object ユーザーID {
        <<value-object>>
    }

    ユーザー "1" o-- "1" ユーザーID
}

' 集約を跨ぐ参照（弱い参照）
ユーザー集約.ユーザー "0..*" o-- "0..*" メディア集約.メディアID : お気に入り、あとでみる

@enduml
