@startuml

participant クライアント
participant サーバー
database データベース

break リクエストにセッションを含まない
    クライアント <-- サーバー: 401 認証失敗
end
サーバー -> データベース: セッションが有効かチェック
サーバー <-- データベース: チェック結果
break セッションが無効
    クライアント <-- サーバー: 401 認証失敗
end

@enduml
