@startuml

title patch /api/media/{mediaId}

クライアント -> サーバー: リクエスト
!include ./auth_guard.puml

participant クライアント
participant サーバー
database ストレージ
database データベース

サーバー -> データベース: トランザクション開始
サーバー -> データベース: メディアを更新
サーバー <-- データベース: 更新完了
サーバー -> データベース: メディアの整合性をチェック
サーバー <-- データベース: チェック完了
サーバー -> ストレージ: アイテムを更新
サーバー <-- ストレージ: 更新完了
break メディア更新失敗 or アイテム更新失敗 or メディア整合性なし
    サーバー -> ストレージ: アイテムを削除
    サーバー <-- ストレージ: 削除完了
    サーバー -> データベース: ロールバック
    サーバー <-- データベース: ロールバック完了
    クライアント <-- サーバー: 200 失敗
end
サーバー -> データベース: コミット
サーバー <-- データベース: コミット完了

クライアント <-- サーバー: 200 成功

@enduml
