@startuml

title post /media

クライアント -> サーバー: リクエスト
!include ./auth_guard.puml

participant クライアント
participant サーバー
database ストレージ
database データベース

サーバー -> データベース: トランザクション開始
サーバー -> データベース: メディアを登録
サーバー <-- データベース: 登録完了
サーバー -> ストレージ: アイテムを保存
サーバー <-- ストレージ: 保存完了
break メディア、アイテム保存に失敗
    サーバー -> ストレージ: アイテムを削除
    サーバー <-- ストレージ: 削除完了
    サーバー -> データベース: ロールバック
    サーバー <-- データベース: ロールバック完了
    クライアント <-- サーバー: 200 失敗
end
サーバー -> データベース: コミット
サーバー <-- データベース: コミット完了

クライアント <-- サーバー: 200 成功

@enduml
