@startuml

title put /api/favorite/{mediaId}

!include ../participants.puml

クライアント -> Controller: リクエスト

note over Controller, データベース
    セッションチェック
end note

Controller -> Service: お気に入り追加処理
Service -> infrastructure: トランザクション開始
infrastructure -> データベース: トランザクション開始

Service -> Repository: メディアの存在チェック
Repository -> データベース: メディアの存在チェック
Repository <-- データベース: メディアの存在結果
Service <-- Repository: メディアの存在結果

break メディアが存在しない
    Service -> infrastructure: ロールバック
    infrastructure -> データベース: ロールバック
    Controller <-- Service: お気に入り追加失敗
    クライアント <-- Controller: 200 失敗
end

Service -> Domain: お気に入り作成
Service <-- Domain: お気に入りドメイン
Service -> Repository: お気に入り保存
Repository -> データベース: お気に入り保存
Service <-- Repository: お気に入り保存完了

break お気に入り保存に失敗
    Service -> infrastructure: ロールバック
    infrastructure -> データベース: ロールバック
    Controller <-- Service: お気に入り追加失敗
    クライアント <-- Controller: 200 失敗
end

Service -> infrastructure: コミット
infrastructure -> データベース: コミット
Controller <-- Service: お気に入り追加成功
クライアント <-- Controller: 200 成功

@enduml
