@startuml

title delete /api/queue/{mediaId}

!include ../participants.puml

クライアント -> Controller: リクエスト

note over Controller, データベース
    セッションチェック
end note

Controller -> Service: あとで見る削除処理
Service -> infrastructure: トランザクション開始
infrastructure -> データベース: トランザクション開始

Service -> Repository: あとで見る取得
Repository -> データベース: あとで見る取得
Repository <-- データベース: あとで見る情報
Service <-- Repository: あとで見るドメイン

break あとで見るが存在しない
    Service -> infrastructure: ロールバック
    infrastructure -> データベース: ロールバック
    Controller <-- Service: あとで見る削除失敗
    クライアント <-- Controller: 200 失敗
end

Service -> Domain: あとで見る無効化
Service -> Repository: あとで見る保存
Repository -> データベース: あとで見る保存
Service <-- Repository: あとで見る保存完了

break あとで見る保存に失敗
    Service -> infrastructure: ロールバック
    infrastructure -> データベース: ロールバック
    Controller <-- Service: あとで見る削除失敗
    クライアント <-- Controller: 200 失敗
end

Service -> infrastructure: コミット
infrastructure -> データベース: コミット
Controller <-- Service: あとで見る削除成功
クライアント <-- Controller: 200 成功

@enduml
