@startuml
package "Domain Layer" {
  !include ./aggregate.puml
  !include ./domainService.puml
  !include ./repositoryImplement.puml

  TagService *-u- "Aggregate.Tag Aggregate.Tag"
  TagService *-- TagRepositoryImplement
  FavoriteService *-u- Favorite
  FavoriteService *-- FavoriteRepositoryImplement
  QueueService *-u- Queue
  QueueService *-- QueueRepositoryImplement
}
@enduml