openapi: 3.1.0
info:
  title: Media App API
  version: 1.0.0
servers:
  - url: https://example.com
paths:
  /:
    $ref: './paths/screen/root.yaml'
  /screen/summary:
    $ref: './paths/screen/summary.yaml'
  /screen/detail/{mediaId}:
    $ref: './paths/screen/detail.mediaId.yaml'
  /screen/viewer/{mediaId}/{mediaPage}:
    $ref: './paths/screen/viewer.mediaId.mediaPage.yaml'
  /screen/search:
    $ref: './paths/screen/search.yaml'
  /screen/error:
    $ref: './paths/screen/error.yaml'
  /screen/entry:
    $ref: './paths/screen/entry.yaml'
  /screen/edit/{mediaId}:
    $ref: './paths/screen/edit.mediaId.yaml'

  /api/media:
    $ref: './paths/api/media.yaml'
  /api/media/{mediaId}:
    $ref: './paths/api/media.mediaId.yaml'

components:
  responses:
    RedirectError:
      description: エラー画面リダイレクト
      headers:
        Location:
          description: リダイレクト先のURL
          schema:
            type: string
            example: /error
