@startuml

title あとで見る登録

actor 閲覧者
participant ブラウザ
participant サーバー

閲覧者 -> ブラウザ: あとで見るボタン押下
ブラウザ -> サーバー: あとで見る登録\nput /api/queue/{mediaId}
ブラウザ <-- サーバー: レスポンス
ブラウザ -> ブラウザ: あとで見るボタンを登録状態に変更
閲覧者 <- ブラウザ: 変更後の画面を表示

@enduml
