@startuml

title サムネイル押下

actor 閲覧者
participant ブラウザ
participant サーバー

閲覧者 -> ブラウザ: サムネイル押下
ブラウザ -> サーバー: ビューアー画面取得\nget /viewer/{mediaId}/{mediaPage}
ブラウザ <-- サーバー: ビューアー画面HTML
閲覧者 <- ブラウザ: ビューアー画面を表示

@enduml
