@startuml

title タグ検索

actor 閲覧者
participant ブラウザ
participant サーバー

閲覧者 -> ブラウザ: タグ押下
ブラウザ -> サーバー: メディア一覧画面取得\nget /summary?tags=[{カテゴリー名}:{ラベル名}]
ブラウザ <-- サーバー: メディア一覧画面HTML
閲覧者 <- ブラウザ: メディア一覧画面を表示

@enduml
