@startuml

title メディア検索

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: 検索ボタン押下

ブラウザ -> サーバー: メディア一覧画面取得\nget /summary?title={タイトル}&tags=[{カテゴリー名}:{タグ名}]
note over ブラウザ
    summaryPage、sortはデフォルト値を使うので不要
end note
ブラウザ <-- サーバー: メディア一覧画面HTML
ユーザー <- ブラウザ: メディア一覧画面を表示

@enduml
