@startuml

title get /detail/{mediaId}

participant クライアント
participant サーバー
database データベース

クライアント -> サーバー: リクエスト
!include ./auth_guard.puml

サーバー -> データベース: メディアを取得
サーバー <-- データベース: メディア情報

クライアント <-- サーバー: メディア詳細画面HTML

@enduml
