@startuml

title ログイン

actor ユーザー
participant ブラウザ
participant サーバー

ユーザー -> ブラウザ: ログインボタン押下
ブラウザ -> サーバー: ログイン認証\npost /api/login
ブラウザ <-- サーバー: レスポンス
alt ログイン成功
    ブラウザ -> サーバー: メディア一覧画面取得\nget /summary
    ブラウザ <-- サーバー: メディア一覧画面HTML
    ユーザー <- ブラウザ: メディア一覧画面を表示
else
    ユーザー <- ブラウザ: ログイン失敗を表示
end

@enduml
