@startuml 

title 上ページと入れ替え

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: メディアファイル番号入れ替え下ボタン押下
ブラウザ -> ブラウザ: 1つ大きいページのメディアファイルと位置を入れ替える
ブラウザ -> ブラウザ: ページ番号を1増やす
ブラウザ -> ブラウザ: 入れ替えたメディアファイルのページ番号を1減らす
ユーザー <- ブラウザ: 変更後の画面を表示

@enduml
