@startuml 

title ファイル選択

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: ファイル選択エリア押下
ユーザー <- ブラウザ: ファイル選択ダイアログを表示
ユーザー -> ブラウザ: ファイルを選択
ブラウザ -> ブラウザ: 選択されたファイルをメディアファイルとして一番下に追加
ユーザー <- ブラウザ: 変更後の画面を表示

@enduml
