@startuml 

title メディア登録

actor ユーザー
participant ブラウザ

ユーザー -> ブラウザ: メディア登録ボタン押下

ブラウザ -> サーバー: メディア登録\npost /api/media
ブラウザ <-- サーバー: レスポンス
alt メディア登録成功
    ブラウザ -> サーバー: メディア一覧画面取得\nget /detail/media/{mediaId}
    ブラウザ <-- サーバー: メディア一覧画面HTML
    ユーザー <- ブラウザ: メディア一覧画面を表示
else
    ユーザー <- ブラウザ: 登録失敗を表示
end

@enduml
